# Install and test and OMERO plugin e.g. a Web app, a CLI plugin or a library
#
# This workflow will install omero-test-infra, start an OMERO environment
# including database, server and web deployment, configure the OMERO plugin
# and run integration tests.
#
# 1. Set up the stage variable depending on the plugin. Supported stages
# are: app, cli, scripts, lib, srv
#
# 2. Adjust the cron schedule as necessary

name: OMERO
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    name: Run integration tests against OMERO
    runs-on: ubuntu-latest
    env:
      STAGE: app
    steps:
      - uses: actions/checkout@v4
      - name: Checkout omero-test-infra
        uses: actions/checkout@master
        with:
          repository: ome/omero-test-infra
          path: .omero
          ref: ${{ secrets.OMERO_TEST_INFRA_REF }}
      - name: Install ontop-cli
        run:
          - curl -L https://github.com/ontop/ontop/releases/download/ontop-5.2.0/ontop-cli-5.2.0.zip
          - mkdir -p ontop-cli
          - cd ontop-cli
          - unzip ../ontop-cli-5.2.0.zip
          - cd jdbc
          - curl -L https://jdbc.postgresql.org/download/postgresql-42.7.4.jar
          - cd ../..
          - ls -R ontop-cli
      - name: Build and run OMERO tests
        run: .omero/docker $STAGE
