# Install and test and OMERO plugin e.g. a Web app, a CLI plugin or a library
#
# This workflow will install omero-test-infra, start an OMERO environment
# including database, server and web deployment, configure the OMERO plugin
# and run integration tests.
#
# 1. Set up the stage variable depending on the plugin. Supported stages
# are: app, cli, scripts, lib, srv
#
# 2. Adjust the cron schedule as necessary

name: OMERO
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    name: Run integration tests against OMERO
    runs-on: ubuntu-latest
    env:
      STAGE: app
      NOCLEAN: true
      VERBOSE: true
    steps:
      - uses: actions/checkout@v4
      - name: Checkout omero-test-infra
        uses: actions/checkout@master
        with:
          repository: ome/omero-test-infra
          path: .omero
          ref: ${{ secrets.OMERO_TEST_INFRA_REF }}
      - name: Install java
        run: sudo apt install default-jdk -y
      - name: Install omero-py
        run: ci_utils/install_omero-py.sh
      - name: ontop-cli
        run: ci_utils/install_ontop.sh
      - name: patch portmapping
        run: cp ci_utils/portmapping.patch .omero && cd .omero && patch -p1 < portmapping.patch && git diff
      - name: srv-test
        run: .omero/docker run srv test
      - name: Launch omero, insert data and launch ontop
        run: bash ci_utils/omero-ontop.sh
